version: '3'

services:

    mariadb:
        image: mariadb:10.3.9
        container_name: ${APP_NAME:?err}-mariadb
        ports:
          - '3306:3306'
        restart: 'on-failure'
        environment:
          MYSQL_DATABASE: ${MYSQL_DATABASE:?err}
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
        volumes:
          - ${PWD}